steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/cocktail-api-project/cocktail-api-repo/backend-app'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'europe-central2-docker.pkg.dev/cocktail-api-project/cocktail-api-repo/backend-app'

  - name: 'gcr.io/google-cloud-sdk/gcloud'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cocktail-api-service'
      - '--image'
      - 'europe-central2-docker.pkg.dev/cocktail-api-project/cocktail-api-repo/backend-app'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-central2-docker.pkg.dev/cocktail-api-project/cocktail-api-repo/backend-app'
